### ISSUE TITLE
No syntax highlighting

### ISSUE THREAD

**Issue by djangoliv** [attakei/sphinx-revealjs#117]
I try with this section:

```
Test
----

.. revealjs-code-block:: python
   :data-line-numbers: 1

   def hello():
       print("world")
```

The result in html code is
```
<pre data-id="test">
<code data-trim="" data-noescape="" class="python" data-line-numbers="1">def hello():
    print("world")</code>
</pre>
```
But All is grey :(

I use Python 3.9.2

$ pip list
Package                       Version
----------------------------- -----------
alabaster                     0.7.12
Babel                         2.10.1
certifi                       2022.5.18.1
charset-normalizer            2.0.12
docutils                      0.17.1
idna                          3.3
imagesize                     1.3.0
importlib-metadata            4.11.4
Jinja2                        3.1.2
MarkupSafe                    2.1.1
packaging                     21.3
pip                           20.3.4
pkg-resources                 0.0.0
Pygments                      2.12.0
pyparsing                     3.0.9
pytz                          2022.1
requests                      2.27.1
setuptools                    44.1.1
snowballstemmer               2.2.0
Sphinx                        4.5.0
sphinx-revealjs               1.5.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
urllib3                       1.26.9
zipp                          3.8.0

Regards

**Comment by attakei** [comment]
Please check values of `revealjs_script_plugins` and `revealjs_css_files` in `conf.py`.

`sphinx-revealjs` uses revealjs plugin for syntax highlighting instead of pygment.
To work rightly in your documentation, you need set these;

- Add settings for `RevealHighlight` into `revealjs_script_plugins`
- Add highlighting theme css file into `revealjs_css_files`
 
Example: https://github.com/attakei/sphinx-revealjs/blob/master/demo/revealjs4/conf.py

**Comment by djangoliv** [comment]
@attakei Thanks, it works.
